Exercise 2 done
mohit-loconav/training pull request #2
Opened 2021-03-14 16:46 UTC by mohit-loconav

2021-03-14 16:47 UTC, mohit-loconav commented
PTAL @gagan93jtg

2021-03-15 05:18 UTC, gagan93jtg requested changes

2021-03-15 05:18 UTC, gagan93jtg commented on html/Exercise 2/index.html
> +        /* body {
**Generic Issues**: unrequired spacing, commented lines, 2 space indentation

2021-03-15 05:18 UTC, gagan93jtg commented on html/Exercise 2/index.html
> +            font-family: 'Muli',sans-serif;
Use **Raleway**

2021-03-15 08:12 UTC, gagan93jtg requested changes

2021-03-15 08:12 UTC, gagan93jtg commented on html/Exercise 2/index.html
> +      font-family: 'Raleway',sans-serif;
check the design once. Entire design is so less in font weight that I can barely read anything
![Uploading Screenshot 2021-03-15 at 1.42.34 PM.png…]()

2021-03-15 11:22 UTC, gagan93jtg approved these changes

2021-03-15 11:24 UTC, merged